#pragma once
#include "Solar/sol_table_file.h"
#include "Solar/sol_assert.h"
#include "Utils/Logger.h"
#include "Utils/Logger.h"
#include "DataDefine.h"
#include "Solar/sol_table.h"
#include "Solar/sol_table_file.h"
#include "Solar/sol_assert.h"

#include "Table/Table_NpcAIBehavior.h"
#include "Table/Table_NpcAICondition.h"
#include "Table/Table_NpcAIGoalSensor.h"
#include "Table/Table_NpcAIPolicy.h"
#include "Table/Table_NpcAIPolicyRoot.h"
